from django.db import models

# Create your models here.

class Project(models.Model):
    name = ...
    description = ...
    owner = ...
    created_at = ...
    github_url = ...
    status = ...
    participants = ...
    skills = ...



class Skill(models.Model):
    name = ...
