from django.db import models

# Create your models here.

class User(models.Model):
    email = ...
    name = ...
    surname = ...
    avatar = ...
    phone = ...
    github_url = ...
    about = ...
    is_active = ...
    is_staff = ...
    